### ISSUE TITLE
Edit header partial to make subdomain work

### ISSUE THREAD

**Issue by yohandsome** [miaskiewicz/systemic-skin-care-review-csv-to-json#1]
For systemicskincare.skinbypom.com to work, the following needs to be added to the <head> of each page: <base href="http://createcosmetics.com/systemicskincare/{{page.title}}" />

For the landing page it should just be: <base href="http://createcosmetics.com/systemicskincare" />

**Comment by miaskiewicz** [comment]
You created this issue by adding base href; removing base href will solve this problem.  It's not in the checked in code so I'm closing this issue.

**Comment by yohandsome** [comment]
Some more explanation is due here, this is a feature request that enables us to use the systemicskincare.skinbypom.com subdomain with systemicskincare hosted on createcosmetics.com's server.

To make the address bar in your browser show the correct subdomain url, e.g. systemicskincare.skinbypom.com/methodology, instead of createcosmetics.com/systemicskincare/methodology the index.html in /methododology on the server needs <base href="http://createcosmetics.com/systemicskincare/methodology"> added in the header, same goes for the home page and all other pages respectively.

This works after I modified the domain root .htaccess to contain:

RewriteEngine on
RewriteCond %{HTTP_HOST} ^skinbypom\.com$
RewriteRule ^systemicskincare(/(.*))? http://systemicskincare.skinbypom.com/$2 [QSA,L,R=301]

So the header partial needs to be modified to add the correct base href for each page generated.

**Comment by miaskiewicz** [comment]
Can you just set up a hosting account instead for the other domain? This shouldn't incur any extra charges and using this tag is non standard.



—

**Comment by miaskiewicz** [comment]
I don't even think you need to setup a separate domain nor include this tag to make this work, so probably should re-close this issue.



—

**Comment by yohandsome** [comment]
Here's a description of the issue with the fix I tested: http://stackoverflow.com/questions/18826921/subdomain-redirect-with-htaccess-without-changing-url-in-the-address-bar

Will contact bluehost tomorrow morning to see if this can be worked around without needing a new hosting account.

**Comment by miaskiewicz** [comment]
I have no idea why you need the base href tag though.  This tag is only
needed for relative URLs.

The original CSS URLs were not relative and based on the root of the
current domain.  I had to alter these because you wanted me to throw it
online in a sub-directory rather than the root directory (for the
YCombinator app).  There is no reason to use this tag going forward.

On Tue, Apr 7, 2015 at 12:52 AM, yohandsome <notifications@github.com>
wrote:

> Here's a description of the issue with the fix I tested:
> http://stackoverflow.com/questions/18826921/subdomain-redirect-with-htaccess-without-changing-url-in-the-address-bar
>
> Will contact bluehost tomorrow morning to see if this can be worked around
> without needing a new hosting account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miaskiewicz/systemic-skin-care-review-csv-to-json/issues/1#issuecomment-90434465>
> .
>



-- 
grzegorz miąskiewicz
+1 415 413 8332

**Comment by yohandsome** [comment]
Problem is that root is the createcosmetics.com domain, not skinbypom.com.

Maybe I'm being a complete noob here, but subdomain redirects don't work

**Comment by miaskiewicz** [comment]
You are being a noob, closing.
